manala:
  repository: https://github.com/loic-roux-404/manala-recipes
  recipe: ops.playbook

repository_save: https://github.com/loic-roux-404/manala-recipes
gitignore: ""

ansible: 
  auto_tag: false
  cfg_lines:
      vault_password_file: ./vault_pass.sh
  internal_roles: false
  inventory: ./inventories/dev/

vagrant: 
  project_name: playbook-template
  box: loic-roux-404/deb64-buster
  box_update: false
  box_version: null
  vb_guest_update: false
  domain: loicroux.test
  git: 
    org: loic-roux-404
    provider: https://github.com
  paths: 
    guest: /vagrant
    host: ./
    web: ""
  network: 
    dns: true
    fix_routing: true
    ip: 192.168.33.10
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: public 
  ansible: 
    disabled: true
    inventory: ./inventory/dev
    playbook: ""
    playbook_version: master
    sub_playbook: site.yml
    type: local
    vars:
        keyboard_mac: false
  fs: 
    opts:
        disabled: true
        ignored:
            - /**/.DS_Store
            - .git
            - .vagrant
            - .idea/
            - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
  provider:  
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: "on"
    type: virtualbox
