manala:
  repository: http://github.com/loic-roux-404/manala-recipes.git
  recipe: ops.playbook

repository_save: /Users/loic/Ops/manala-recipes
recipe_save: ops.playbook
gitignore: ''

ansible:
  auto_tag: false
  internal_roles: false
  inventory: ./inventories/dev/
  cfg_lines:
        vault_password_file: ./vault_pass.sh

vagrant:
  project_name: playbook-template
  box: loic-roux-404/deb64-buster
  box_update: false
  box_version: null
  vb_guest_update: false
  domain: loicroux.test
  git:
    org: loic-roux-404
    provider: https://github.com
  paths:
    guest: /vagrant
    host: ./
    web: ""
  network:
    dns: true
    ip: 192.168.33.10
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: public
  ansible:
    disabled: true
    inventory: ./inventory/dev
    playbook: ""
    sub_playbook: site.yml
    type: local
    vars:
        keyboard_mac: false
  fs:
    opts:
        disabled: true
        ignored:
          - /**/.DS_Store
          - .git
          - .vagrant
          - .idea/
          - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
  provider:
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: on
    type: virtualbox
